### ISSUE TITLE
fix the scroll to top part(has a lot of white space below)  and also try to align the black bars after about us and all with the below line's black dividers

### ISSUE THREAD

**Issue by Devesh21700Kumar** [Aviral09/DevSocHackathon#33]
![image](https://user-images.githubusercontent.com/59202075/111995661-2f6ff900-8b3f-11eb-9042-42c8553d7cbc.png)

![image](https://user-images.githubusercontent.com/59202075/111995698-3991f780-8b3f-11eb-918d-e0080ff2892f.png)

**Comment by Aviral09** [comment]
Redone
